# Generated by Django 5.2.6 on 2025-09-05 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_2_modelo_1', models.CharField(max_length=200)),
                ('campo_3_modelo_1', models.TextField(default='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_3_modelo_2', models.DateField()),
                ('campo_4_modelo_2', models.TimeField()),
                ('campo_5_modelo_2', models.DateTimeField()),
                ('campo_6_modelo_2', models.IntegerField()),
                ('campo_7_modelo_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campo_8_modelo_2', models.FloatField()),
                ('campo_9_modelo_2', models.BooleanField()),
                ('campo_10_modelo_2', models.EmailField(max_length=254)),
                ('campo_11_modelo_2', models.URLField()),
                ('campo_12_modelo_2', models.URLField()),
                ('campo_13_modelo_2', models.ImageField(upload_to='images/')),
                ('campo_2_modelo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.modelo_1')),
            ],
        ),
    ]
